name = "Business Basic"
license = "MIT"
licenselink = "https://github.com/gillulyit/business-basic/blob/main/LICENSE"
description = "A theme created for Gilluly IT Services, but shared with the world."

# Taxonomy terms
tags = ["responsive", "company"]
features = ["responsive", "logo", "shortcodes"]

# If the theme has a single author
[author]
  name = "Gilluly IT Services"
  homepage = "https://www.gillulyit.com"
